# Generated by Django 5.2.3 on 2025-07-30 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="dayly_notification_time",
            field=models.TimeField(
                default=datetime.time(8, 30, 27, 250529),
                verbose_name="Время по умолчанию ежедневного напоминания в телеграме о привычках",
            ),
        ),
    ]
