# Generated by Django 5.2.3 on 2025-07-30 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_dayly_notification_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="dayly_notification_time",
            field=models.TimeField(
                default=datetime.time(8, 30, 9, 79708),
                verbose_name="Время по умолчанию ежедневного напоминания в телеграме о привычках",
            ),
        ),
    ]
