# Generated by Django 5.2.3 on 2025-08-22 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_dayly_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dayly_notification_time',
            field=models.TimeField(default=datetime.time(8, 30, 54, 453520), verbose_name='Время по умолчанию ежедневного напоминания в телеграме о привычках'),
        ),
    ]
