networks:
  my_network:
    driver: bridge
services:
  db:
    image: postgres:17.1-alpine
    restart: always
    networks:
      - my_network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    networks:
      - my_network
    expose:
      - 6379
    volumes:
      - redis_data:/data

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 --access-logfile - config.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    networks:
      - my_network
    expose:
      - 8000
    depends_on:
      - db
      - redis
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_BACKEND: "redis://redis:6379/0"
      DATABASE_URL: "postgres://hhuser:123456@db:5432/habitz"

  nginx:
    image: nginx:1.28-alpine
    networks:
      - my_network
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/var/www/static/:ro
    depends_on:
      - web
  celery:
    build: .
    entrypoint: celery
    command: -A config worker --loglevel=info
    networks:
      - my_network
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=False
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgres://hhuser:123456@db:5432/habitz
      - SECRET_KEY="django-insecure-g_4li039o4ja=7sbSodoun=8i5=e_xuz_k!)e^um%+fg2j94p)"
    depends_on:
      - web
      - redis
    links:
    - redis
  beat:
    build: .
    entrypoint: celery
    networks:
      - my_network
    command: -A config beat --loglevel=info
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=False
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgres://hhuser:123456@db:5432/habitz
      - SECRET_KEY="django-insecure-g_4li039o4ja=7sbSodoun=8i5=e_xuz_k!)e^um%+fg2j94p)"
    depends_on:
      - web
      - redis
    links:
    - redis
volumes:
  postgres_data:
  redis_data:
  static_volume:
