services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    expose:
      - 6379
    volumes:
      - redis_data:/data

  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 --access-logfile - config.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db
      - redis
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_BACKEND: "redis://redis:6379/0"
      DATABASE_URL: "postgres://hhuser:123456@db:5432/habitz"

  nginx:
    image: nginx:1.28-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/var/www/static/:ro
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
  static_volume:
