services:
  db:
    build:
      dockerfile: Dockerfile_postgres
      context: '.'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: '123456'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./restore_db.sh:/docker-entrypoint-initdb.d/restore_db.sh

  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_BACKEND: "redis://redis:6379/0"
      DATABASE_URL: "postgres://hhuser:123456@db:5432/habitz"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  postgres_data:
  static: