# Generated by Django 5.2.3 on 2025-07-30 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие — действие, которое представляет собой привычка",
                "verbose_name_plural": "действия",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Описание"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True, verbose_name="когда необходимо выполнять привычку"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        auto_now_add=True,
                        verbose_name="дата начала выполнения для не ежедневных привычек",
                    ),
                ),
                (
                    "notification_time",
                    models.TimeField(
                        default=datetime.time(8, 30, 34, 165831),
                        verbose_name="Время напоминания в телеграме",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=True, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "frequency",
                    models.IntegerField(
                        default=1,
                        verbose_name="Периодичность выполнения привычки в днях",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=120, verbose_name="Время на выполнение в секундах"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "привычки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Описание"
                    ),
                ),
                (
                    "preposition",
                    models.CharField(blank=True, max_length=10, verbose_name="Предлог"),
                ),
            ],
            options={
                "verbose_name": "Место, в котором необходимо выполнять привычку",
                "verbose_name_plural": "места",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вознаграждение — чем пользователь должен себя вознаградить после выполнения",
                "verbose_name_plural": "вознаграждение",
                "ordering": ["name"],
            },
        ),
    ]
