# Generated by Django 5.2.3 on 2025-08-10 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="notification_time",
            field=models.TimeField(
                default=datetime.time(8, 30, 12, 532843),
                verbose_name="Время напоминания в телеграме",
            ),
        ),
    ]
