# Generated by Django 5.2.3 on 2025-07-30 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_reward_owner_alter_habit_notification_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="notification_time",
            field=models.TimeField(
                default=datetime.time(8, 30, 6, 164548),
                verbose_name="Время напоминания в телеграме",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="start_date",
            field=models.DateField(
                auto_now_add=True,
                null=True,
                verbose_name="дата начала выполнения для не ежедневных привычек",
            ),
        ),
    ]
