# Generated by Django 5.2.3 on 2025-08-21 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_habit_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='notification_time',
            field=models.TimeField(default=datetime.time(8, 30, 29, 700853), verbose_name='Время напоминания в телеграме'),
        ),
    ]
