# Generated by Django 5.2.3 on 2025-08-22 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0031_alter_habit_notification_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="notification_is_scheduled",
            field=models.BooleanField(
                default=False, verbose_name="Оповещение уже запланировано"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="notification_time",
            field=models.TimeField(
                default=datetime.time(8, 30, 52, 228538),
                verbose_name="Время напоминания в телеграме",
            ),
        ),
    ]
