# Generated by Django 5.2.3 on 2025-08-22 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_habit_notification_is_scheduled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='notification_time',
            field=models.TimeField(default=datetime.time(8, 30, 19, 191206), verbose_name='Время напоминания в телеграме'),
        ),
    ]
